version: '3.7'

services:
  debug:
    build:
      context: .
      dockerfile: debug.Dockerfile
    command: -workspaceName "dev" -planPath plan.out
    ports:
      - "9001:9000"
      - "2345:2345"